name: KakaoGroup Publish
on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setting environment variables
        run: echo "VITE_CLIENT_KEY=$KAKAO_CLIENT_KEY" >> .env
        env:
        KAKAO_CLIENT_KEY: ${{ secrets.KAKAO_CLIENT_KEY }}

      - name: InstallDependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: publish Project
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KAKAO_WEB_PAGE_KEY }}
          publish_dir: ./dist
